# Jekyll configuration for GitHub Pages
title: "Background Remover API"
description: "AI-powered background removal service"

# Exclude Python files and other non-web assets from the site
exclude:
  - "*.py"
  - "requirements.txt"
  - "Dockerfile"
  - "docker-compose.yml"
  - ".env*"
  - "*.sh"
  - "__pycache__/"
  - "*.pyc"
  - ".vscode/"
  - ".git/"
  - ".gitignore"
  - "render.yaml"
  - "start.sh"
  - "run.sh"
  - "configure_deployment.sh"

# Include these files in the site
include:
  - "_*"
  - ".nojekyll"

# Use minimal theme for better compatibility
theme: minima

# Disable Jekyll processing for certain files
plugins:
  - jekyll-feed

# Markdown processor
markdown: kramdown

# Site URL (will be set automatically by GitHub Pages)
url: ""
baseurl: ""
