version: '3.8'

services:
  bg-remover-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./data/bg_remover.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    
  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Add your SSL certificates here
    depends_on:
      - bg-remover-api
    restart: unless-stopped
