services:
  # Backend API Service
  - type: web
    name: bg-remover-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
    
  # Frontend Static Site
  - type: web
    name: bg-remover-frontend
    runtime: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
