services:
  # Backend API Service
  - type: web
    name: bg-remover-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
    
  # Frontend Static Site
  - type: web
    name: bg-remover-frontend
    runtime: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
