services:
  # Backend API Service
  - type: web
    name: bg-remover-api
    runtime: python3
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONOPTIMIZE
        value: "1"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "65536"
    
  # Frontend Static Site
  - type: web
    name: bg-remover-frontend
    runtime: static
    buildCommand: ls -la && echo "Static site - no build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
